=== swedenconnect/eidas-eu-mock/EIDAS-Sources-2.6.0/EIDAS-SpecificCommunicationDefinition/src/main/resources/xsds/lightResponse.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright (c) 2020 by European Commission
  ~
  ~ Licensed under the EUPL, Version 1.2 or - as soon they will be
  ~ approved by the European Commission - subsequent versions of the
  ~ EUPL (the "Licence");
  ~ You may not use this work except in compliance with the Licence.
  ~ You may obtain a copy of the Licence at:
  ~ https://joinup.ec.europa.eu/page/eupl-text-11-12
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the Licence is distributed on an "AS IS" basis,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
  ~ implied.
  ~ See the Licence for the specific language governing permissions and
  ~ limitations under the Licence.
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://cef.eidas.eu/LightResponse"
		   elementFormDefault="qualified" version="1.2">
	<xs:element name="lightResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">Internal unique ID</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="inResponseToId" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">The original unique ID of the Request this Response is issued for</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="consent" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">The consent of the principal.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:anyURI">
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:consent:unspecified"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:consent:obtained"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:consent:prior"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:consent:current-implicit"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:consent:current-explicit"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:consent:unavailable"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:consent:inapplicable"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="issuer" type="xs:string" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">Issuer of the LightRequest or originating SP - not used</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ipAddress" type="xs:string" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">Optional IP address of the user agent as seen on IdP</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="relayState" type="xs:string" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">Optional state information to return to the Consumer.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="subject" type="xs:string" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">Subject of the Assertion for the eIDAS SAML Response.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="subjectNameIdFormat" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">Format of the identifier attribute.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:1.1:nameid-format:WindowsDomainQualifiedName"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:nameid-format:kerberos"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"/>
							<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:nameid-format:encrypted"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="levelOfAssurance" type="xs:anyURI" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">
							Level of assurance required to fulfill the request
							Either notified level of assurance matching the following:
							<xs:restriction base="xs:string">
								<xs:enumeration value="http://eidas.europa.eu/LoA/low"/>
								<xs:enumeration value="http://eidas.europa.eu/LoA/substantial"/>
								<xs:enumeration value="http://eidas.europa.eu/LoA/high"/>
							</xs:restriction>
							Or non notified level of assurance being an URI having a different prefix than
							http://eidas.europa.eu/LoA
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="status" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation xml:lang="en">Complex element to provide status information from IdP</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="failure" type="xs:boolean" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>Value "true" represents that the authentication request is failed</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="statusCode" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>SAML2 defined status code</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:status:Success">
											<xs:annotation>
												<xs:documentation>Authentication success</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
										<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:status:Requester">
											<xs:annotation>
												<xs:documentation>Authentication failure: the requester did something wrong</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
										<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:status:Responder">
											<xs:annotation>
												<xs:documentation>Authentication failure: error at the the responder side</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
										<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:status:VersionMismatch">
											<xs:annotation>
												<xs:documentation>Authentication failure: The responder could not process the request because the request message's version was incorrect.</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="subStatusCode" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>Optional SAML2 defined sub status code used in case of failure</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:status:AuthnFailed"/>
										<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:status:InvalidAttrNameOrValue"/>
										<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy"/>
										<xs:enumeration value="urn:oasis:names:tc:SAML:2.0:status:RequestDenied"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="statusMessage" type="xs:string" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>An optional status message</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="attributes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="definition" type="xs:string" minOccurs="1" maxOccurs="1"/>
										<xs:element name="value" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== swedenconnect/eidas-eu-mock/EIDAS-Sources-2.5.0-SNAPSHOT-MDSL/EIDAS-Parent/src/test/resources/LightResponseTestCases/consent/invalidNonExistingConsent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2020 by European Commission
  ~
  ~ Licensed under the EUPL, Version 1.2 or - as soon they will be
  ~ approved by the European Commission - subsequent versions of the
  ~ EUPL (the "Licence");
  ~ You may not use this work except in compliance with the Licence.
  ~ You may obtain a copy of the Licence at:
  ~ https://joinup.ec.europa.eu/page/eupl-text-11-12
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the Licence is distributed on an "AS IS" basis,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
  ~ implied.
  ~ See the Licence for the specific language governing permissions and
  ~ limitations under the Licence.
  -->
<lightResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://cef.eidas.eu/LightResponse"
               xsi:schemaLocation="http://cef.eidas.eu/LightResponse ../../../../main/resources/xsds/lightResponse.xsd">
    <id>f5e7e0f5-b9b8-4256-a7d0-4090141b326d</id>
    <inResponseToId>x4e7e0f5-b9b8-4256-a7d0-4090141b320u</inResponseToId>
    <consent>not:consent:uri</consent>
    <issuer>http://localhost:7001/SP/metadata</issuer>
    <ipAddress>127.0.0.1</ipAddress>
    <relayState>MyRelayState</relayState>
    <subject>ES/FI/0123456</subject>
    <subjectNameIdFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</subjectNameIdFormat>
    <levelOfAssurance>http://eidas.europa.eu/LoA/low</levelOfAssurance>
    <status>
        <failure>false</failure>
        <statusCode>urn:oasis:names:tc:SAML:2.0:status:Success</statusCode>
    </status>
    <attributes>
    </attributes>
</lightResponse>
